from typing import Protocol, List, Optional
from .entity import Agente

class AgenteRepository(Protocol):
    async def create(self, agente: Agente) -> Agente:
        ...
    async def list_all(self) -> List[Agente]:
        ...
    async def update(self, agent: Agente) -> Agente:
        ...
    async def getByName(self, name: str) -> Agente:
        ...
    async def getByElement(self, element: str) -> List[Agente]:
        ...